services:
  # Development service with hot-reloading
  docusaurus-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./site:/app
    environment:
      - NODE_ENV=development
    security_opt:
      - no-new-privileges:true

  docusaurus-prod-local:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: serve
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    security_opt:
      - no-new-privileges:true

  # Production service
  docusaurus-prod:
    image: ghcr.io/devinci-fablab/documentation:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 2
    security_opt:
      - no-new-privileges:true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.my-website.rule=Host(`docs.devinci-fablab.fr`)'
      - 'traefik.http.routers.my-website.entrypoints=websecure'
      - 'traefik.http.routers.my-website.tls.certresolver=myresolver'
      - 'traefik.http.services.my-website.loadbalancer.server.port=3000'
      - 'com.centurylinklabs.watchtower.enable=true'
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
