services:
  # Development service with hot-reloading
  docusaurus-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    restart: unless-stopped
    expose:
      - '3000'
    volumes:
      - ./site:/app
    environment:
      - NODE_ENV=development
    security_opt:
      - no-new-privileges:true
    networks:
      Vaultwarden:
        ipv4_address: 192.168.5.3


  # Production service
  docusaurus-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: serve
    restart: unless-stopped
    expose:
      - '3000'
    environment:
      - NODE_ENV=production
    security_opt:
      - no-new-privileges:true
    networks:
      Vaultwarden:
        ipv4_address: 192.168.5.3

networks:
  Vaultwarden:
    external: true