services:
  # Development service with hot-reloading
  docusaurus-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    restart: unless-stopped
    expose:
      - '3000'
    volumes:
      - ./site:/app
    environment:
      - NODE_ENV=development
    security_opt:
      - no-new-privileges:true
    networks:
      Documentation:
        ipv4_address: 192.168.6.2

  # Production service
  docusaurus-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: serve
    restart: unless-stopped
    expose:
      - '3000'
    environment:
      - NODE_ENV=production
    security_opt:
      - no-new-privileges:true
    networks:
      Documentation:
        ipv4_address: 192.168.6.2

networks:
  Documentation:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.6.0/24
          gateway: 192.168.6.1
