services:
  docusaurus-dev:
    container_name: documentation-docusaurus-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ../site:/app
    environment:
      - NODE_ENV=development

networks:
  traefik-network:
    external: true
